create table databaseschema
(
    fieldid          smallint    not null
        constraint databaseschema_pkey
            primary key,
    schemacategoryid smallint    not null
        constraint databaseschema_schemacategoryid_fkey
            references schemacategory,
    schematableid    smallint    not null
        constraint databaseschema_schematableid_fkey
            references schematable,
    field            varchar(50) not null,
    datatypeid       smallint    not null
        constraint databaseschema_datatypeid_fkey
            references datatype,
    fieldlength      varchar(10),
    isunique         boolean     not null,
    iskey            boolean     not null,
    required         boolean     not null,
    linktableid      smallint
        constraint databaseschema_linktableid_fkey
            references schematable,
    fielddescription varchar(255)
);

alter table databaseschema
    owner to postgres;

INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (1, 1, 11, 'disturbanceID', 6, 'NA', true, true, true, null, 'Unique integer key value per disturbance.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (2, 1, 11, 'disturbance', 7, '50', true, false, true, null, 'One to two word description of primary disturbance processes.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (3, 1, 12, 'drainageID', 6, 'NA', true, true, true, null, 'Unique integer key value per drainage.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (4, 1, 12, 'drainage', 7, '50', true, false, true, null, 'One to two word description of water drainage regime.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (5, 1, 13, 'environmentID', 5, 'NA', true, true, true, null, 'Unique integer key value per environmental site observation.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (6, 1, 13, 'projectID', 6, 'NA', false, true, true, 27, 'Foreign key value that links environmental observations to project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (7, 1, 13, 'siteID', 4, 'NA', false, true, true, 33, 'Foreign key value that links environmental observations to site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (8, 1, 13, 'envObserveDate', 2, 'NA', false, false, true, null, 'Date of observation.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (9, 1, 13, 'envObserverID', 6, 'NA', false, true, true, 23, 'Foreign key value that identifies primary environmental observer.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (10, 1, 13, 'soilObserverID', 6, 'NA', false, true, false, 23, 'Foreign key value that identifies primary soils observer.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (11, 1, 13, 'strataID', 6, 'NA', false, true, false, null, 'Foreign key value that identifies site strata.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (12, 1, 13, 'physiographyID', 6, 'NA', false, true, false, 25, 'Foreign key value that identifies site physiography.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (13, 1, 13, 'geomorphologyID', 6, 'NA', false, true, false, 15, 'Foreign key value that identifies geomorphology (surface terrain).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (14, 1, 13, 'macrotopographyID', 6, 'NA', false, true, false, 18, 'Foreign key value that identifies macrotopography descriptor.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (15, 1, 13, 'microtopographyID', 6, 'NA', false, true, false, 19, 'Foreign key value that identifies microtopography descriptor.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (16, 1, 13, 'microrelief', 3, '4,1', false, false, false, null, 'Approximate mean deviation from neutral in within-site surface elevation measured in centimeters (cm).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (17, 1, 13, 'drainageID', 6, 'NA', false, true, false, 12, 'Foreign key value that identifies drainage regime.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (18, 1, 13, 'moistureID', 6, 'NA', false, true, false, 20, 'Foreign key value that identifies moisture regime.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (19, 1, 13, 'soilClassID', 6, 'NA', false, true, false, 34, 'Foreign key value that identifies soil class.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (20, 1, 13, 'depthWater', 3, '4,1', false, false, false, null, 'Mean depth of water table from soil surface measured in centimeters (cm) with positive values indicating above surface depth and negative values indicating below surface depth.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (21, 1, 13, 'depthMossDuff', 3, '4,1', false, false, false, null, 'Mean depth of live moss and/or lichen (including both live and undecomposed dead) and duff (recognizable decomposed dead vegetation) measure in centimeters (cm).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (22, 1, 13, 'depthRestrictiveLayer', 3, '4,1', false, false, false, null, 'Mean depth to restrictive layer (if present within uppermost meter of soil) from soil surface measured in centimeters (cm).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (23, 1, 13, 'restrictiveTypeID', 6, 'NA', false, true, false, 29, 'Foreign key value that identifies the type of restrictive layer encountered.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (24, 1, 13, 'soilPH10', 3, '4,2', false, false, false, null, 'Soil pH at 10 cm.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (25, 1, 13, 'conductivity10', 3, '7,2', false, false, false, null, 'Soil conductivity at 10 cm.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (26, 1, 13, 'temperature10', 3, '5,2', false, false, false, null, 'Soil temperature (°C) at 10 cm.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (27, 1, 13, 'soilPH30', 3, '4,2', false, false, false, null, 'Soil pH at 30 cm.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (28, 1, 13, 'conductivity30', 3, '7,2', false, false, false, null, 'Soil conductivity at 30 cm.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (29, 1, 13, 'temperature30', 3, '5,2', false, false, false, null, 'Soil temperature in °C at 30 cm.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (30, 1, 13, 'waterPH', 3, '4,2', false, false, false, null, 'Surface water pH (if water above soil surface is present).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (31, 1, 13, 'waterConductivity', 3, '7,2', false, false, false, null, 'Surface water conductivity (if water above soil surface is present).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (32, 1, 13, 'waterTemperature', 3, '5,2', false, false, false, null, 'Surface water temperature in °C (if water above soil surface is present).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (33, 1, 13, 'disturbanceID', 6, 'NA', false, true, false, 11, 'Foreign key value that identifies descriptor of primary disturbance processes.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (34, 1, 13, 'homogenous', 1, 'NA', false, false, true, null, 'Boolean value with 0 representing sites with non-homogenous vegetation and 1 representing sites where the dominant vegetation is homogenous.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (35, 1, 15, 'geomorphologyID', 6, 'NA', true, true, true, null, 'Unique integer key value per geomorphic surface.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (36, 1, 15, 'geomorphology', 7, '50', true, false, true, null, 'One to two word descriptor of primary geomorphic surface form and deposition process.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (37, 1, 18, 'macrotopographyID', 6, 'NA', true, true, true, null, 'Unique integer key value per macrotopography descriptor.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (38, 1, 18, 'macrotopography', 7, '50', true, false, true, null, 'One to several word descriptor of surface shape and texture on a scale larger than the plot (hundreds of meters).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (39, 1, 19, 'microtopographyID', 6, 'NA', true, true, true, null, 'Unique integer key value per microtopography descriptor.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (40, 1, 19, 'microtopography', 7, '50', true, false, true, null, 'One to several word descriptor of surface shape and texture on a scale smaller than the plot (meters or less).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (41, 1, 20, 'moistureID', 6, 'NA', true, true, true, null, 'Unique integer key value per moisture regime.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (42, 1, 20, 'moisture', 7, '50', true, false, true, null, 'One to two word description of moisture regime.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (43, 1, 25, 'physiographyID', 6, 'NA', true, true, true, null, 'Unique integer key value per physiography.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (44, 1, 25, 'physiography', 7, '30', true, false, true, null, 'One to two word general description of landscape position and form.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (45, 1, 29, 'restrictiveTypeID', 6, 'NA', true, true, true, null, 'Unique integer key value per restrictive layer type.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (46, 1, 29, 'restrictiveType', 7, '150', true, false, true, null, 'Full name of type of restrictive layer.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (47, 1, 34, 'soilClassID', 6, 'NA', true, true, true, null, 'Unique integer key value per soil class.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (48, 1, 34, 'soilClass', 7, '50', true, false, true, null, 'Several word descriptor for general soil class based on soil taxonomy.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (49, 1, 35, 'strataID', 6, 'NA', true, true, true, null, 'Unique integer key value per stratification unit.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (50, 1, 35, 'strata', 7, '50', true, false, true, null, 'Stratification unit as defined in the original project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (51, 2, 3, 'completionID', 6, 'NA', true, true, true, null, 'Unique integer key value per completion value.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (52, 2, 3, 'completion', 7, '30', true, false, true, null, 'Completion value indicating project status.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (53, 2, 7, 'dictionaryID', 4, 'NA', true, true, true, null, 'Unique integer key value per constrained data attribute.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (54, 2, 7, 'fieldID', 6, 'NA', false, true, true, 8, 'Foreign key value that identifies the schema category to which a particular data attribute belongs.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (55, 2, 7, 'attributeID', 4, 'NA', false, false, true, null, 'Key value used for a particular attribute in a particular constraint table.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (56, 2, 7, 'attribute', 7, '120', false, false, true, null, 'Valid attribute value character string in a constraint table. These are the possible data values that can populate a particular constrained field.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (57, 2, 8, 'fieldID', 6, 'NA', true, true, true, null, 'Unique integer key value per schema table-field combination.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (58, 2, 8, 'schemaCategoryID', 6, 'NA', false, true, true, 30, 'Foreign key value that identifies the schema category to which a particular field belongs.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (59, 2, 8, 'schemaTableID', 6, 'NA', false, true, true, 31, 'Foreign key value that identifies the schema table to which a particular field belongs.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (60, 2, 8, 'field', 7, '50', false, false, true, null, 'Field name in database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (61, 2, 8, 'dataTypeID', 6, 'NA', false, true, true, 9, 'Foreign key value that identifies the data type stored in the field.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (62, 2, 8, 'fieldLength', 7, '10', false, false, false, null, 'Integer value representing the maximum possible character length stored in the field.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (63, 2, 8, 'isUnique', 1, 'NA', false, false, true, null, 'Boolean value indicating whether the field requires unique entries or not.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (64, 2, 8, 'isKey', 1, 'NA', false, false, true, null, 'Boolean value indicating whether the field contains key values or not.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (65, 2, 8, 'required', 1, 'NA', false, false, true, null, 'Boolean value indicating whether the field requires values or accepts null.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (66, 2, 8, 'linkTableID', 6, 'NA', false, false, false, 31, 'Foreign key value that identifies the table in which a foreign key identifies a primary key value.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (67, 2, 8, 'fieldDescription', 7, '255', false, false, true, null, 'Description of the data stored in the field.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (68, 2, 9, 'dataTypeID', 6, 'NA', true, true, true, null, 'Unique integer key value of the data type stored in the field.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (69, 2, 9, 'dataType', 7, '80', true, true, true, null, 'Name of the data type stored in the field.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (70, 2, 23, 'personnelID', 6, 'NA', true, true, true, null, 'Unique integer key value per person.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (71, 2, 23, 'personnel', 7, '50', true, false, true, null, 'First name and last name of person.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (72, 2, 30, 'schemaCategoryID', 6, 'NA', true, true, true, null, 'Unique integer key value per schema category.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (73, 2, 30, 'schemaCategory', 7, '80', true, false, true, null, 'One word description of the purpose of the data stored in a particular field.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (74, 2, 31, 'schemaTableID', 6, 'NA', true, true, true, null, 'Unique integer key value per name of table in database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (75, 2, 31, 'schemaTable', 7, '80', true, false, true, null, 'Name of table in database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (76, 3, 21, 'organizationID', 6, 'NA', true, true, true, null, 'Unique integer key value per organization.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (77, 3, 21, 'organization', 7, '250', true, false, true, null, 'Full name of organization.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (78, 3, 21, 'organizationAbbr', 7, '20', true, false, true, null, 'Abbreviated name of organzition.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (79, 3, 21, 'organizationTypeID', 6, 'NA', false, true, true, null, 'Foreign key value that identifies the organization type of the organization.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (80, 3, 22, 'organizationTypeID', 6, 'NA', true, true, true, null, 'Unique integer key value per organization type.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (81, 3, 22, 'organizationType', 7, '50', true, false, true, null, 'One to two word description of organization type.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (82, 3, 27, 'projectID', 6, 'NA', true, true, true, null, 'Unique integer key value per project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (83, 3, 27, 'originatorID', 6, 'NA', false, true, true, 21, 'Foreign key value that identifies the organization that originated the data.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (84, 3, 27, 'funderID', 6, 'NA', false, true, true, 21, 'Foreign key value that identifies the organization that provided the primary funding for the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (85, 3, 27, 'managerID', 6, 'NA', false, true, true, 23, 'Foreign key value that identifies the person with primary responsibility for leading the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (86, 3, 27, 'projectName', 7, '250', true, false, true, null, 'Full title of the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (87, 3, 27, 'projectNameAbbr', 7, '20', true, false, true, null, 'Shortened name of the project to be used for convenience.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (88, 3, 27, 'completionID', 6, 'NA', false, true, true, 3, 'Foreign key value that identifies the status of the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (89, 3, 27, 'yearStart', 6, 'NA', false, false, true, null, 'Four digit year of the start of field data collection for the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (90, 3, 27, 'yearEnd', 6, 'NA', false, false, false, null, 'Four digit year of the end of field data collection for the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (91, 3, 27, 'projectDescription', 7, '255', true, false, true, null, 'Description of the purpose, method, and (anticipated) outcome of the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (92, 3, 28, 'projectStatusID', 6, 'NA', true, true, true, null, 'Unique integer key value per project status.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (93, 3, 28, 'projectID', 6, 'NA', true, true, true, 27, 'Foreign key value that identifies the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (94, 3, 28, 'projectModified', 2, 'NA', false, false, true, null, 'Date of most recent update to the project metadata for the project in the database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (95, 3, 28, 'siteModified', 2, 'NA', false, false, false, null, 'Date of most recent update to the site data for the project in the database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (96, 3, 28, 'coverModified', 2, 'NA', false, false, false, null, 'Date of most recent update to the foliar cover data for the project in the database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (97, 3, 28, 'environmentModified', 2, 'NA', false, false, false, null, 'Date of most recent update to the environment data for the project in the database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (98, 3, 28, 'modifiedByID', 6, 'NA', false, true, true, 23, 'Foreign key value that identifies the person who most recently updated any of the project data in the database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (99, 4, 5, 'coverMethodID', 6, 'NA', true, true, true, null, 'Unique integer key value per cover estimation method.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (100, 4, 5, 'coverMethod', 7, '50', true, false, true, null, 'One to several word descriptor of method used to estimate foliar cover.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (101, 4, 10, 'datumID', 6, 'NA', true, true, true, null, 'Unique integer key value per datum.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (102, 4, 10, 'datum', 7, '10', true, false, true, null, 'Five character EPSG geographic horizontal datum abbreviation.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (103, 4, 24, 'perspectiveID', 6, 'NA', true, true, true, null, 'Unique integer key value per perspective.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (104, 4, 24, 'perspective', 7, '50', true, false, true, null, 'One word descriptor of the viewing perspective of the vegetation observer.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (105, 4, 26, 'plotDimensionsID', 6, 'NA', true, true, true, null, 'Unique integer key value per plot size and shape.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (106, 4, 26, 'plotDimensions', 7, '20', true, false, true, null, 'Description of plot size and shape either as a set of two numbers or as a single number radius, where all numbers are measured as meters (m).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (107, 4, 32, 'scopeID', 6, 'NA', true, true, true, null, 'Unique integer key value per scope category.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (108, 4, 32, 'scope', 7, '30', true, false, true, null, 'One to several word description of species-level vegetation survey intensity.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (109, 4, 33, 'siteID', 4, 'NA', true, true, true, null, 'Unique integer key value per site, where site is the unique combination of physical location, plot size, and survey methods.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (110, 4, 33, 'siteCode', 7, '50', true, false, true, null, 'Unique alpha-numeric identifier assigned to the site or plot in the project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (111, 4, 33, 'projectID', 6, 'NA', false, true, true, 27, 'Foreign key value that identifies the project for which the site was initially sampled.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (112, 4, 33, 'perspectiveID', 6, 'NA', false, true, true, 24, 'Foreign key value that identifies the viewing perspective of the vegetation observer at the site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (113, 4, 33, 'coverMethodID', 6, 'NA', false, true, true, 5, 'Foreign key value that identifies the cover estimation method used to sample vegetation at the site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (114, 4, 33, 'scopeVascularID', 6, 'NA', false, true, true, 32, 'Foreign key value that identifies the survey intensity of vascular plants at the site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (115, 4, 33, 'scopeBryophyteID', 6, 'NA', false, true, true, 32, 'Foreign key value that identifies the survey intensity of bryophytes at the site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (116, 4, 33, 'scopeLichenID', 6, 'NA', false, true, true, 32, 'Foreign key value that identifies the survey intensity of lichens at the site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (117, 4, 33, 'plotDimensionsID', 6, 'NA', false, true, true, 26, 'Foreign key value that identifies the plot dimensions at the site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (118, 4, 33, 'datumID', 6, 'NA', false, true, true, 10, 'Foreign key value that identifies the geographic horizontal datum of the site position.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (119, 4, 33, 'latitude', 3, '12,9', false, false, true, null, 'Latitude in decimal degrees with up to 6 decimal places.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (120, 4, 33, 'longitude', 3, '12,9', false, false, true, null, 'Longitude in decimal degrees with up to 6 decimal places.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (121, 4, 33, 'error', 3, '6,2', false, false, true, null, 'Error in meters (m) of position fix.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (122, 5, 1, 'author', 7, '120', true, false, true, null, 'Abbreviated authorship set.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (123, 5, 1, 'authorID', 4, 'NA', true, true, true, null, 'Unique integer key value per authorship set.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (124, 5, 2, 'category', 7, '30', true, false, true, null, 'Life form category.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (125, 5, 2, 'categoryID', 6, 'NA', true, true, true, null, 'Unique integer key value per life form category.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (126, 5, 14, 'family', 7, '80', true, false, true, null, 'Full name of the taxonomic family.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (127, 5, 14, 'familyID', 6, 'NA', true, true, true, null, 'Unique integer key value per taxonomic family.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (128, 5, 16, 'habit', 7, '80', true, false, true, null, 'Growth habit descriptor.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (129, 5, 16, 'habitID', 6, 'NA', true, true, true, null, 'Unique integer key value per growth habit.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (130, 5, 17, 'categoryID', 6, 'NA', false, true, true, 2, 'Foreign key value that identifies the life form category that encompasses the accepted genus.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (131, 5, 17, 'familyID', 6, 'NA', false, true, true, 14, 'Foreign key value that identifies the family that encompasses the accepted genus.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (132, 5, 17, 'genusAccepted', 7, '50', true, false, true, null, 'Full name of accepted genus.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (133, 5, 17, 'hierarchyID', 6, 'NA', true, true, true, null, 'Unique integer key value per accepted genus.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (134, 5, 36, 'acceptedID', 4, 'NA', true, true, true, null, 'Unique integer key value per taxon, inclusive of infraspecies, species, genera, and general life form codes.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (135, 5, 36, 'authAcceptedID', 4, 'NA', false, true, false, 1, 'Foreign key value that identifies the author for the taxon.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (136, 5, 36, 'habitID', 6, 'NA', false, true, false, 16, 'Foreign key value that identifies the primary growth habit typical of the taxon throughout the majority of its range in Northwestern North America.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (137, 5, 36, 'hierarchyID', 6, 'NA', false, true, false, 17, 'Foreign key value that identifies the hierarchy of the taxon genus.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (138, 5, 36, 'levelID', 6, 'NA', false, true, false, 38, 'Foreign key value that identifies the taxonomic level of the accepted taxon.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (139, 5, 36, 'linkSource', 7, '255', true, false, false, null, 'Html link to the primary name source that defines the taxon concept applied in the database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (140, 5, 36, 'nameAccepted', 7, '120', true, false, true, null, 'Taxon name, inclusive of infraspecies, species, genera, and general life form codes.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (141, 5, 36, 'native', 1, 'NA', false, false, true, null, 'Boolean value with 1 indicating that the taxon is native in Alaska, which is not exclusive to the taxon also being non-native in Alaska.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (142, 5, 36, 'non_native', 1, 'NA', false, false, true, null, 'Boolean value with 1 indicating that the taxon is non-native in Alaska, which is not exclusive to the taxon also being native in Alaska.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (143, 5, 36, 'taxonSourceID', 6, 'NA', false, true, false, 39, 'Foreign key value that identifies the primary name source defining the taxon concept applied in the database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (144, 5, 37, 'acceptedID', 4, 'NA', false, true, true, 36, 'Foreign key value that identifies the accepted name to which the adjudicated name should refer.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (145, 5, 37, 'adjudicatedID', 4, 'NA', true, true, true, null, 'Unique integer key value per taxon name that has been applied in Alaska (includes accepted names, synonyms, misapplied names, and orthographic variants).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (146, 5, 37, 'authAdjudicatedID', 4, 'NA', false, true, false, 1, 'Foreign key value that identifies the author for the taxon.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (147, 5, 37, 'nameAdjudicated', 7, '120', true, false, true, null, 'Taxon name that has been applied in Alaska (includes accepted names, synonyms, misapplied names, and orthographic variants).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (148, 5, 37, 'statusAdjudicatedID', 6, 'NA', false, true, false, 40, 'Foreign key value that identifies the taxonomic status of the name.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (149, 5, 38, 'level', 7, '30', true, false, true, null, 'Taxonomic level of name.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (150, 5, 38, 'levelID', 6, 'NA', true, true, true, null, 'Unique integer key value per taxonomic level.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (151, 5, 39, 'citation', 7, '500', true, false, true, null, 'Full citation for source of taxon concept applied in database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (152, 5, 39, 'taxonSource', 7, '50', true, false, true, null, 'Short reference for source of taxon concept applied in database.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (153, 5, 39, 'taxonSourceID', 6, 'NA', true, true, true, null, 'Unique integer key value per name source.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (154, 5, 40, 'taxonStatus', 7, '30', true, false, true, null, 'One to two word description of the taxonomic status of the name.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (155, 5, 40, 'taxonStatusID', 6, 'NA', true, true, true, null, 'Unique integer key value per taxon status.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (156, 6, 4, 'coverID', 5, 'NA', true, true, true, null, 'Unique integer key value per species abundance observation.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (157, 6, 4, 'siteID', 4, 'NA', false, true, true, 33, 'Foreign key value that links abundance observations to site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (158, 6, 4, 'projectID', 6, 'NA', false, true, true, 27, 'Foreign key value that links abundance observations to project.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (159, 6, 4, 'vegObserveDate', 2, 'NA', false, false, true, null, 'Date of observation.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (160, 6, 4, 'vegObserverID', 6, 'NA', false, true, true, 23, 'Foreign key value that identifies primary vegetation observer.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (161, 6, 4, 'vegRecorderID', 6, 'NA', false, true, false, 23, 'Foreign key value that identifies secondary vegetation observer (e.g., recorder).');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (162, 6, 4, 'coverTypeID', 6, 'NA', false, true, true, 6, 'Foreign key value that links cover type to site.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (163, 6, 4, 'nameOriginal', 7, '120', false, false, true, null, 'Unconstrained taxon name for original identification.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (164, 6, 4, 'adjudicatedID', 3, '6,3', false, true, true, null, 'Foreign key value that identifies the adjudicated taxon name.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (165, 6, 6, 'coverTypeID', 6, 'NA', true, true, true, null, 'Unique integer key value per cover type.');
INSERT INTO public.databaseschema (fieldid, schemacategoryid, schematableid, field, datatypeid, fieldlength, isunique, iskey, required, linktableid, fielddescription) VALUES (166, 6, 6, 'coverType', 7, '50', true, false, true, null, 'One to several word descriptor of cover type.');